/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

#include "stm32_utils.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void) {
    // Select HSI as clock source.
    // rcc.cfgr.mco1.set_hsi();
    set_bits(rcc_cfgr_addr, rcc_cfgr_mco1_bit, rcc_cfgr_mco1_bitcnt, rcc_cfgr_mco1_hsi_value);

    // Enable GPIOA peripheral clock.
    // gpio_a.enable_clock();
    set_bit(rcc_ahb1enr_addr, rcc_ahb1enr_gpioaen_bit);
    // Set GPIOA pin 8 mode to alternate function mode.
    // gpio_a.pin<8>.mode.set_alt_fun();
    set_bits(gpioa_modereg_addr, gpiox_modereg_moder8_bit, gpiox_modereg_moderx_bit_cnt, gpiox_modereg_moderx_altfunc_value);
    // Select alternate function mode 0 for GPIOA pin 8.
    // gpio_a.pin<8>.mode.set_alt_fun().set_mode0();
    set_bits(gpioa_altfunhireg_addr, gpiox_altfunhireg_afr8_bit, gpiox_altfunhireg_afr8_bit_cnt, gpiox_altfunhireg_afr8_af0_value);

    /* Loop forever */
    for (;;)
        ;
}
